### ISSUE TITLE
Add default module loader for script handlin

### ISSUE THREAD

**Issue by gabrielstuff** [soixantecircuits/neodymium#7]
Sometime, you need to use script that are not available on npm.
This same script are developped to be used with AMD or requireJS. This could be troubleful. In order to avoid that, you just want to require it and _shim_ it like this : 

`var Draggable = require('exports?Draggable!imports?define=>false,require=>false,module=>false,this=>window!./scripts/vendor/Draggable.min.js')`

Such a require allow you to declare Draggable globaly on window object and loading it by simulating the absence of `require`, `module` and `define`.

But in order to make so you need this specific loader for Webpack : 

`exports-loader`
`script-loader`
`imports-loader`

Thus I would suggest to make them available by default in order to ease the development of everybody. The doc is here : 
https://github.com/webpack/docs/wiki/shimming-modules and of course the doc does not specify that you should install these modules.

Thanks !

**Comment by hugohil** [comment]
FIY I tested `var Draggable = require('script!exports?Draggable!imports?define=>false,require=>false,module=>false,this=>window!./scripts/vendor/Draggable.min.js')` in the entry file and it resulted in an error: `Uncaught ReferenceError: Draggable is not defined`.

Still added the module because they might be useful though.
